name: crappasswd
services:
    crappasswd-builder:
        build:
            context: .
            dockerfile: builder.Dockerfile
        container_name: crappasswd-builder
        env_file:
            - .env
        stdin_open: true
        tty: true
        working_dir: /workspaces/crappasswd
        volumes:
            - $PWD:/workspaces/crappasswd
        user: ${CURRENT_UID}:${CURRENT_GID}
        image: crappasswd-builder:latest
